export const councilMembers = {
    'seniorCouncil': [
      {
        name: "Saksham Checker",
        position: "President",
        image: "/assets/images/team/senior/6.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Saksham Gupta",
        position: "Vice President",
        image: "/assets/images/team/senior/8.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Divyam",
        position: "Treasurer",
        image: "/assets/images/team/senior/4.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Divyam",
        position: "Treasurer",
        image: "/assets/images/team/senior/1.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Divyam",
        position: "Treasurer",
        image: "/assets/images/team/senior/2.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Divyam",
        position: "Treasurer",
        image: "/assets/images/team/senior/3.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Divyam",
        position: "Treasurer",
        image: "/assets/images/team/senior/5.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Divyam",
        position: "Treasurer",
        image: "/assets/images/team/senior/7.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Divyam",
        position: "Treasurer",
        image: "/assets/images/team/senior/Hritik Solanki.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
    ],
    'juniorCouncil': [
      {
        name: "Anuj Singh",
        position: "Non Tech ",
        image: "/assets/images/team/junior/Anuj Singh.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Chaitanya Anand",
        position: "Non Tech ",
        image: "/assets/images/team/junior/Chaitanya Anand.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Vishu Bansal",
        position: "Non Tech ",
        image: "/assets/images/team/junior/Vishu Bansal.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Raj Devanshu",
        position: "Non Tech ",
        image: "/assets/images/team/junior/Raj Devanshu.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Chiranjeevi",
        position: "Non Tech ",
        image: "/assets/images/team/junior/Chiranjeevi.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Hemang Krish",
        position: "Non Tech ",
        image: "/assets/images/team/junior/Hemang Krish.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Muskan",
        position: "Non Tech ",
        image: "/assets/images/team/junior/Muskan.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Rishab Goyal",
        position: "Non Tech ",
        image: "/assets/images/team/junior/Rishab Goyal.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Sagar Yadav",
        position: "Non Tech ",
        image: "/assets/images/team/junior/Sagar Yadav.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Sarthak Sachdeva",
        position: "Non Tech ",
        image: "/assets/images/team/junior/Sarthak Sachdeva.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Shubh Yadav",
        position: "Non Tech ",
        image: "/assets/images/team/junior/Shubh Yadav.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Shwetab",
        position: "Non Tech ",
        image: "/assets/images/team/junior/Shwetab.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Teeksha Harish",
        position: "Non Tech ",
        image: "/assets/images/team/junior/Teeksha Harish.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      {
        name: "Vaibhav Pratap",
        position: "Non Tech ",
        image: "/assets/images/team/junior/Vaibhav Pratap.jpg",
        linkedin: "https://www.linkedin.com/in/rishabh-gupta-7b1b3b1b3/",
      },
      
    ],
  };